language: node_js
node_js:
- '.1'
before_install: npm install -g grunt-cli
install: npm install
env:
  global:
  - secure: LMl74LtbkndvIIKB5WnaLUpq1GtgV+iUAwMoK+ndKupJp/UDAIS/yc3AmdthkzXnfzv4IrxCjELjOf1t5VzLUbFlQiKBX2zCyYdxQXXbkRDgGklIv/Hjf6/bsAI7HaSGUYQDy5cGaLVKwMkNy1qySMAlxdryDWOCH8zsqmA=
  - secure: GKFb/hCz4hXEr9IaTngRosgQgV3yqcZSxb7/Einm8NO4yRl5AwK3qK6/SouwSnSgrgzeOuhAlGu4PN2V6ZFucCFqnilHVw6KHrEZwsmW9KV4WSdwOty/TTZBuoHfyVVFz4XPxyt+cPtYy8aKkFU/lshSbN5pMadUiazaIKhJ5c=
